### ISSUE TITLE
haha forge FluidBuilder go brrr

### ISSUE THREAD

**Issue by EdweldDryTry** [jaskarth/discover#2]
loading error with create 0.5e, flywheel 0.6.5 and discover 0.1.1 only
[crash-2022-11-16_21.11.38-fml.txt](https://github.com/SuperCoder7979/discover/files/10021033/crash-2022-11-16_21.11.38-fml.txt)

**Comment by jaskarth** [comment]
This should be fixed in 0.1.2, thanks for the report!
